spring:
  application:
    name: service1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.wochi.xin/jpa_test?characterEncoding=utf8
    username: root
    password: root
    jpa:
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

server:
  port: 8082